import './globals.css';
import { Amatic_SC, Poppins } from 'next/font/google';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Navigation from '@/components/nav';
import { ClerkProvider } from '@clerk/nextjs';
import UserContext from '@/context/context';

const main = Poppins({
  weight: ['400', '600'],
  subsets: ['latin'],
  variable: '--font-poppins',
});
const heading = Amatic_SC({
  weight: ['400', '700'],
  subsets: ['latin'],
  variable: '--font-amatic',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={`${main.variable} ${heading.variable}`}>
        <UserContext>
          <ClerkProvider>
            <Navigation />
            {children}
          </ClerkProvider>
        </UserContext>
      </body>
    </html>
  );
}
